"""empty message

Revision ID: 65dd87603b22
Revises: 62770250c28f
Create Date: 2016-03-02 17:44:44.193326

"""

# revision identifiers, used by Alembic.
revision = '65dd87603b22'
down_revision = '62770250c28f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('analytics_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'analytics_code')
    ### end Alembic commands ###
