"""empty message

Revision ID: b56cb0a8cab8
Revises: cbd2283ffe71
Create Date: 2016-03-08 21:45:53.900787

"""

# revision identifiers, used by Alembic.
revision = 'b56cb0a8cab8'
down_revision = 'cbd2283ffe71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('guest_author_name', sa.String(), nullable=True),
    sa.Column('guest_author_email', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('create_date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###
