"""empty message

Revision ID: bfeae087d0ac
Revises: None
Create Date: 2016-03-02 20:17:03.917128

"""

# revision identifiers, used by Alembic.
revision = 'bfeae087d0ac'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('testchange', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'testchange')
    ### end Alembic commands ###
