"""empty message

Revision ID: cbd2283ffe71
Revises: f72a069295e0
Create Date: 2016-03-02 20:54:07.626597

"""

# revision identifiers, used by Alembic.
revision = 'cbd2283ffe71'
down_revision = 'f72a069295e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'testchange2')
    op.drop_column('site_settings', 'testchange')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('testchange', sa.VARCHAR(), nullable=True))
    op.add_column('site_settings', sa.Column('testchange2', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
