"""empty message

Revision ID: f72a069295e0
Revises: bfeae087d0ac
Create Date: 2016-03-02 20:23:17.913624

"""

# revision identifiers, used by Alembic.
revision = 'f72a069295e0'
down_revision = 'bfeae087d0ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('testchange2', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'testchange2')
    ### end Alembic commands ###
